language: python

os:
    - linux
    - osx

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

before_install:
    - pip install cython cffi

install:
    - g++ -shared -fPIC rectangle.cpp -o rectangle_cffi.so
    - ls
    - python setup.py build_ext --inplace

script:
    - PYTHONPATH=. py.test test_all.py

notifications:
    email: false
