language: python

os:
    - linux
    - osx

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

before_install:
    - pip install Cython

install:
    - python setup.py build_ext --inplace

script:
    - py.test test_all.py

notifications:
    email: false
